[Shortcut11Icon]
Meter=Image
ImageName=#icon11#
X=10
Y=12R
H=15
W=15
LeftMouseUpAction=["#path11#"]
MouseOverAction=[Play #soundsPath#\hover.wav][!SetOption Shortcut11Icon ImageName #icon11H#][!UpdateMeter Shortcut11Icon][!Redraw][!SetOption Shortcut11 FontColor #colorSecondary#][!UpdateMeter Shortcut11][!Redraw]
MouseLeaveAction=[!SetOption Shortcut11Icon ImageName #icon11#][!UpdateMeter Shortcut11Icon][!Redraw][!SetOption Shortcut11 FontColor #colorMain#][!UpdateMeter Shortcut11][!Redraw]

[Shortcut11]
Meter=String
MeterStyle=styleShortcut
Text=#Text11#
LeftMouseUpAction=["#Path11#"]
MouseOverAction=[Play #soundsPath#\hover.wav][!SetOption Shortcut11Icon ImageName #icon11H#][!UpdateMeter Shortcut11Icon][!Redraw][!SetOption Shortcut11 FontColor #colorSecondary#][!UpdateMeter Shortcut11][!Redraw]
MouseLeaveAction=[!SetOption Shortcut11Icon ImageName #icon11#][!UpdateMeter Shortcut11Icon][!Redraw][!SetOption Shortcut11 FontColor #colorMain#][!UpdateMeter Shortcut11][!Redraw]
X=30
Y=-1r

[Shortcut12Icon]
Meter=Image
ImageName=#icon12#
X=10
Y=12R
H=15
W=15
LeftMouseUpAction=["#path12#"]
MouseOverAction=[Play #soundsPath#\hover.wav][!SetOption Shortcut12Icon ImageName #icon12H#][!UpdateMeter Shortcut12Icon][!Redraw][!SetOption Shortcut12 FontColor #colorSecondary#][!UpdateMeter Shortcut12][!Redraw]
MouseLeaveAction=[!SetOption Shortcut12Icon ImageName #icon12#][!UpdateMeter Shortcut12Icon][!Redraw][!SetOption Shortcut12 FontColor #colorMain#][!UpdateMeter Shortcut12][!Redraw]

[Shortcut12]
Meter=String
MeterStyle=styleShortcut
Text=#text12#
LeftMouseUpAction=["#path12#"]
MouseOverAction=[Play #soundsPath#\hover.wav][!SetOption Shortcut12Icon ImageName #icon12H#][!UpdateMeter Shortcut12Icon][!Redraw][!SetOption Shortcut12 FontColor #colorSecondary#][!UpdateMeter Shortcut12][!Redraw]
MouseLeaveAction=[!SetOption Shortcut12Icon ImageName #icon12#][!UpdateMeter Shortcut12Icon][!Redraw][!SetOption Shortcut12 FontColor #colorMain#][!UpdateMeter Shortcut12][!Redraw]
X=30
Y=-1r

[Shortcut13Icon]
Meter=Image
ImageName=#icon13#
X=10
Y=12R
H=15
W=15
LeftMouseUpAction=["#path13#"]
MouseOverAction=[Play #soundsPath#\hover.wav][!SetOption Shortcut13Icon ImageName #icon13H#][!UpdateMeter Shortcut13Icon][!Redraw][!SetOption Shortcut13 FontColor #colorSecondary#][!UpdateMeter Shortcut13][!Redraw]
MouseLeaveAction=[!SetOption Shortcut13Icon ImageName #icon13#][!UpdateMeter Shortcut13Icon][!Redraw][!SetOption Shortcut13 FontColor #colorMain#][!UpdateMeter Shortcut13][!Redraw]

[Shortcut13]
Meter=String
MeterStyle=styleShortcut
Text=#text13#
LeftMouseUpAction=["#path13#"]
MouseOverAction=[Play #soundsPath#\hover.wav][!SetOption Shortcut13Icon ImageName #icon13H#][!UpdateMeter Shortcut13Icon][!Redraw][!SetOption Shortcut13 FontColor #colorSecondary#][!UpdateMeter Shortcut13][!Redraw]
MouseLeaveAction=[!SetOption Shortcut13Icon ImageName #icon13#][!UpdateMeter Shortcut13Icon][!Redraw][!SetOption Shortcut13 FontColor #colorMain#][!UpdateMeter Shortcut13][!Redraw]
X=30
Y=-1r

[Shortcut14Icon]
Meter=Image
ImageName=#icon14#
X=10
Y=12R
H=15
W=15
LeftMouseUpAction=["#path14#"]
MouseOverAction=[Play #soundsPath#\hover.wav][!SetOption Shortcut14Icon ImageName #icon14H#][!UpdateMeter Shortcut14Icon][!Redraw][!SetOption Shortcut14 FontColor #colorSecondary#][!UpdateMeter Shortcut14][!Redraw]
MouseLeaveAction=[!SetOption Shortcut14Icon ImageName #icon14#][!UpdateMeter Shortcut14Icon][!Redraw][!SetOption Shortcut14 FontColor #colorMain#][!UpdateMeter Shortcut14][!Redraw]

[Shortcut14]
Meter=String
MeterStyle=styleShortcut
Text=#text14#
LeftMouseUpAction=["#path14#"]
MouseOverAction=[Play #soundsPath#\hover.wav][!SetOption Shortcut14Icon ImageName #icon14H#][!UpdateMeter Shortcut14Icon][!Redraw][!SetOption Shortcut14 FontColor #colorSecondary#][!UpdateMeter Shortcut14][!Redraw]
MouseLeaveAction=[!SetOption Shortcut14Icon ImageName #icon14#][!UpdateMeter Shortcut14Icon][!Redraw][!SetOption Shortcut14 FontColor #colorMain#][!UpdateMeter Shortcut14][!Redraw]
X=30
Y=-1r

[Shortcut15Icon]
Meter=Image
ImageName=#icon15#
X=10
Y=12R
H=15
W=15
LeftMouseUpAction=["#path15#"]
MouseOverAction=[Play #soundsPath#\hover.wav][!SetOption Shortcut15Icon ImageName #icon15H#][!UpdateMeter Shortcut15Icon][!Redraw][!SetOption Shortcut15 FontColor #colorSecondary#][!UpdateMeter Shortcut15][!Redraw]
MouseLeaveAction=[!SetOption Shortcut15Icon ImageName #icon15#][!UpdateMeter Shortcut15Icon][!Redraw][!SetOption Shortcut15 FontColor #colorMain#][!UpdateMeter Shortcut15][!Redraw]

[Shortcut15]
Meter=String
MeterStyle=styleShortcut
Text=#text15#
LeftMouseUpAction=["#path15#"]
MouseOverAction=[Play #soundsPath#\hover.wav][!SetOption Shortcut15Icon ImageName #icon15H#][!UpdateMeter Shortcut15Icon][!Redraw][!SetOption Shortcut15 FontColor #colorSecondary#][!UpdateMeter Shortcut15][!Redraw]
MouseLeaveAction=[!SetOption Shortcut15Icon ImageName #icon15#][!UpdateMeter Shortcut15Icon][!Redraw][!SetOption Shortcut15 FontColor #colorMain#][!UpdateMeter Shortcut15][!Redraw]
X=30
Y=-1r

[Shortcut16Icon]
Meter=Image
ImageName=#icon16#
X=10
Y=12R
H=15
W=15
LeftMouseUpAction=["#path16#"]
MouseOverAction=[Play #soundsPath#\hover.wav][!SetOption Shortcut16Icon ImageName #icon16H#][!UpdateMeter Shortcut16Icon][!Redraw][!SetOption Shortcut16 FontColor #colorSecondary#][!UpdateMeter Shortcut16][!Redraw]
MouseLeaveAction=[!SetOption Shortcut16Icon ImageName #icon16#][!UpdateMeter Shortcut16Icon][!Redraw][!SetOption Shortcut16 FontColor #colorMain#][!UpdateMeter Shortcut16][!Redraw]

[Shortcut16]
Meter=String
MeterStyle=styleShortcut
Text=#text16#
LeftMouseUpAction=["#path16#"]
MouseOverAction=[Play #soundsPath#\hover.wav][!SetOption Shortcut16Icon ImageName #icon16H#][!UpdateMeter Shortcut16Icon][!Redraw][!SetOption Shortcut16 FontColor #colorSecondary#][!UpdateMeter Shortcut16][!Redraw]
MouseLeaveAction=[!SetOption Shortcut16Icon ImageName #icon16#][!UpdateMeter Shortcut16Icon][!Redraw][!SetOption Shortcut16 FontColor #colorMain#][!UpdateMeter Shortcut16][!Redraw]
X=30
Y=-1r


[Shortcut17Icon]
Meter=Image
ImageName=#icon17#
X=358
Y=515
H=15
W=15
LeftMouseUpAction=["#path17#"]
MouseOverAction=[Play #soundsPath#\hover.wav][!SetOption Shortcut17Icon ImageName #icon17H#][!UpdateMeter Shortcut17Icon][!Redraw][!SetOption Shortcut17 FontColor #colorSecondary#][!UpdateMeter Shortcut17][!Redraw]
MouseLeaveAction=[!SetOption Shortcut17Icon ImageName #icon17#][!UpdateMeter Shortcut17Icon][!Redraw][!SetOption Shortcut17 FontColor #colorMain#][!UpdateMeter Shortcut17][!Redraw]

[Shortcut17]
Meter=String
MeterStyle=styleShortcutRight
Text=#text17#
LeftMouseUpAction=["#path17#"]
MouseOverAction=[Play #soundsPath#\hover.wav][!SetOption Shortcut17Icon ImageName #icon17H#][!UpdateMeter Shortcut17Icon][!Redraw][!SetOption Shortcut17 FontColor #colorSecondary#][!UpdateMeter Shortcut17][!Redraw]
MouseLeaveAction=[!SetOption Shortcut17Icon ImageName #icon17#][!UpdateMeter Shortcut17Icon][!Redraw][!SetOption Shortcut17 FontColor #colorMain#][!UpdateMeter Shortcut17][!Redraw]
X=-5r
Y=-1r

[Shortcut18Icon]
Meter=Image
ImageName=#icon18#
X=358
Y=12R
H=15
W=15
LeftMouseUpAction=["#path18#"]
MouseOverAction=[Play #soundsPath#\hover.wav][!SetOption Shortcut18Icon ImageName #icon18H#][!UpdateMeter Shortcut18Icon][!Redraw][!SetOption Shortcut18 FontColor #colorSecondary#][!UpdateMeter Shortcut18][!Redraw]
MouseLeaveAction=[!SetOption Shortcut18Icon ImageName #icon18#][!UpdateMeter Shortcut18Icon][!Redraw][!SetOption Shortcut18 FontColor #colorMain#][!UpdateMeter Shortcut18][!Redraw]

[Shortcut18]
Meter=String
MeterStyle=styleShortcutRight
Text=#text18#
LeftMouseUpAction=["#path18#"]
MouseOverAction=[Play #soundsPath#\hover.wav][!SetOption Shortcut18Icon ImageName #icon18H#][!UpdateMeter Shortcut18Icon][!Redraw][!SetOption Shortcut18 FontColor #colorSecondary#][!UpdateMeter Shortcut18][!Redraw]
MouseLeaveAction=[!SetOption Shortcut18Icon ImageName #icon18#][!UpdateMeter Shortcut18Icon][!Redraw][!SetOption Shortcut18 FontColor #colorMain#][!UpdateMeter Shortcut18][!Redraw]
X=-5r
Y=-1r

[Shortcut19Icon]
Meter=Image
ImageName=#icon19#
X=358
Y=12R
H=15
W=15
LeftMouseUpAction=["#path19#"]
MouseOverAction=[Play #soundsPath#\hover.wav][!SetOption Shortcut19Icon ImageName #icon19H#][!UpdateMeter Shortcut19Icon][!Redraw][!SetOption Shortcut19 FontColor #colorSecondary#][!UpdateMeter Shortcut19][!Redraw]
MouseLeaveAction=[!SetOption Shortcut19Icon ImageName #icon19#][!UpdateMeter Shortcut19Icon][!Redraw][!SetOption Shortcut19 FontColor #colorMain#][!UpdateMeter Shortcut19][!Redraw]

[Shortcut19]
Meter=String
MeterStyle=styleShortcutRight
Text=#text19#
LeftMouseUpAction=["#path19#"]
MouseOverAction=[Play #soundsPath#\hover.wav][!SetOption Shortcut19Icon ImageName #icon19H#][!UpdateMeter Shortcut19Icon][!Redraw][!SetOption Shortcut19 FontColor #colorSecondary#][!UpdateMeter Shortcut19][!Redraw]
MouseLeaveAction=[!SetOption Shortcut19Icon ImageName #icon19#][!UpdateMeter Shortcut19Icon][!Redraw][!SetOption Shortcut19 FontColor #colorMain#][!UpdateMeter Shortcut19][!Redraw]
X=-5r
Y=-1r

[Shortcut20Icon]
Meter=Image
ImageName=#icon20#
X=358
Y=12R
H=15
W=15
LeftMouseUpAction=["#path20#"]
MouseOverAction=[Play #soundsPath#\hover.wav][!SetOption Shortcut20Icon ImageName #icon20H#][!UpdateMeter Shortcut20Icon][!Redraw][!SetOption Shortcut20 FontColor #colorSecondary#][!UpdateMeter Shortcut20][!Redraw]
MouseLeaveAction=[!SetOption Shortcut20Icon ImageName #icon20#][!UpdateMeter Shortcut20Icon][!Redraw][!SetOption Shortcut20 FontColor #colorMain#][!UpdateMeter Shortcut20][!Redraw]

[Shortcut20]
Meter=String
MeterStyle=styleShortcutRight
Text=#text20#
LeftMouseUpAction=["#path20#"]
MouseOverAction=[Play #soundsPath#\hover.wav][!SetOption Shortcut20Icon ImageName #icon20H#][!UpdateMeter Shortcut20Icon][!Redraw][!SetOption Shortcut20 FontColor #colorSecondary#][!UpdateMeter Shortcut20][!Redraw]
MouseLeaveAction=[!SetOption Shortcut20Icon ImageName #icon20#][!UpdateMeter Shortcut20Icon][!Redraw][!SetOption Shortcut20 FontColor #colorMain#][!UpdateMeter Shortcut20][!Redraw]
X=-5r
Y=-1r

[Shortcut21Icon]
Meter=Image
ImageName=#icon21#
X=358
Y=12R
H=15
W=15
LeftMouseUpAction=["#path21#"]
MouseOverAction=[Play #soundsPath#\hover.wav][!SetOption Shortcut21Icon ImageName #icon21H#][!UpdateMeter Shortcut21Icon][!Redraw][!SetOption Shortcut21 FontColor #colorSecondary#][!UpdateMeter Shortcut21][!Redraw]
MouseLeaveAction=[!SetOption Shortcut21Icon ImageName #icon21#][!UpdateMeter Shortcut21Icon][!Redraw][!SetOption Shortcut21 FontColor #colorMain#][!UpdateMeter Shortcut21][!Redraw]

[Shortcut21]
Meter=String
MeterStyle=styleShortcutRight
Text=#text21#
LeftMouseUpAction=["#path21#"]
MouseOverAction=[Play #soundsPath#\hover.wav][!SetOption Shortcut21Icon ImageName #icon21H#][!UpdateMeter Shortcut21Icon][!Redraw][!SetOption Shortcut21 FontColor #colorSecondary#][!UpdateMeter Shortcut21][!Redraw]
MouseLeaveAction=[!SetOption Shortcut21Icon ImageName #icon21#][!UpdateMeter Shortcut21Icon][!Redraw][!SetOption Shortcut21 FontColor #colorMain#][!UpdateMeter Shortcut21][!Redraw]
X=-5r
Y=-1r

[Shortcut22Icon]
Meter=Image
ImageName=#icon22#
X=358
Y=12R
H=15
W=15
LeftMouseUpAction=["#path22#"]
MouseOverAction=[Play #soundsPath#\hover.wav][!SetOption Shortcut22Icon ImageName #icon22H#][!UpdateMeter Shortcut22Icon][!Redraw][!SetOption Shortcut22 FontColor #colorSecondary#][!UpdateMeter Shortcut22][!Redraw]
MouseLeaveAction=[!SetOption Shortcut22Icon ImageName #icon22#][!UpdateMeter Shortcut22Icon][!Redraw][!SetOption Shortcut22 FontColor #colorMain#][!UpdateMeter Shortcut22][!Redraw]

[Shortcut22]
Meter=String
MeterStyle=styleShortcutRight
Text=#text22#
LeftMouseUpAction=["#path22#"]
MouseOverAction=[Play #soundsPath#\hover.wav][!SetOption Shortcut22Icon ImageName #icon22H#][!UpdateMeter Shortcut22Icon][!Redraw][!SetOption Shortcut22 FontColor #colorSecondary#][!UpdateMeter Shortcut22][!Redraw]
MouseLeaveAction=[!SetOption Shortcut22Icon ImageName #icon22#][!UpdateMeter Shortcut22Icon][!Redraw][!SetOption Shortcut22 FontColor #colorMain#][!UpdateMeter Shortcut22][!Redraw]
X=-5r
Y=-1r