[Shortcut1Icon]
Meter=Image
ImageName=#icon1#
X=10
Y=12R
H=15
W=15
LeftMouseUpAction=["#path1#"]
MouseOverAction=[Play #soundsPath#\hover.wav][!SetOption Shortcut1Icon ImageName #icon1H#][!UpdateMeter Shortcut1Icon][!Redraw][!SetOption Shortcut1 FontColor #colorSecondary#][!UpdateMeter Shortcut1][!Redraw]
MouseLeaveAction=[!SetOption Shortcut1Icon ImageName #icon1#][!UpdateMeter Shortcut1Icon][!Redraw][!SetOption Shortcut1 FontColor #colorMain#][!UpdateMeter Shortcut1][!Redraw]

[Shortcut1]
Meter=String
MeterStyle=styleShortcut
Text=#Text1#
LeftMouseUpAction=["#Path1#"]
MouseOverAction=[Play #soundsPath#\hover.wav][!SetOption Shortcut1Icon ImageName #icon1H#][!UpdateMeter Shortcut1Icon][!Redraw][!SetOption Shortcut1 FontColor #colorSecondary#][!UpdateMeter Shortcut1][!Redraw]
MouseLeaveAction=[!SetOption Shortcut1Icon ImageName #icon1#][!UpdateMeter Shortcut1Icon][!Redraw][!SetOption Shortcut1 FontColor #colorMain#][!UpdateMeter Shortcut1][!Redraw]
X=30
Y=-1r

[Shortcut2Icon]
Meter=Image
ImageName=#icon2#
X=10
Y=12R
H=15
W=15
LeftMouseUpAction=["#path2#"]
MouseOverAction=[Play #soundsPath#\hover.wav][!SetOption Shortcut2Icon ImageName #icon2H#][!UpdateMeter Shortcut2Icon][!Redraw][!SetOption Shortcut2 FontColor #colorSecondary#][!UpdateMeter Shortcut2][!Redraw]
MouseLeaveAction=[!SetOption Shortcut2Icon ImageName #icon2#][!UpdateMeter Shortcut2Icon][!Redraw][!SetOption Shortcut2 FontColor #colorMain#][!UpdateMeter Shortcut2][!Redraw]

[Shortcut2]
Meter=String
MeterStyle=styleShortcut
Text=#text2#
LeftMouseUpAction=["#path2#"]
MouseOverAction=[Play #soundsPath#\hover.wav][!SetOption Shortcut2Icon ImageName #icon2H#][!UpdateMeter Shortcut2Icon][!Redraw][!SetOption Shortcut2 FontColor #colorSecondary#][!UpdateMeter Shortcut2][!Redraw]
MouseLeaveAction=[!SetOption Shortcut2Icon ImageName #icon2#][!UpdateMeter Shortcut2Icon][!Redraw][!SetOption Shortcut2 FontColor #colorMain#][!UpdateMeter Shortcut2][!Redraw]
X=30
Y=-1r

[Shortcut3Icon]
Meter=Image
ImageName=#icon3#
X=10
Y=12R
H=15
W=15
LeftMouseUpAction=["#path3#"]
MouseOverAction=[Play #soundsPath#\hover.wav][!SetOption Shortcut3Icon ImageName #icon3H#][!UpdateMeter Shortcut3Icon][!Redraw][!SetOption Shortcut3 FontColor #colorSecondary#][!UpdateMeter Shortcut3][!Redraw]
MouseLeaveAction=[!SetOption Shortcut3Icon ImageName #icon3#][!UpdateMeter Shortcut3Icon][!Redraw][!SetOption Shortcut3 FontColor #colorMain#][!UpdateMeter Shortcut3][!Redraw]

[Shortcut3]
Meter=String
MeterStyle=styleShortcut
Text=#text3#
LeftMouseUpAction=["#path3#"]
MouseOverAction=[Play #soundsPath#\hover.wav][!SetOption Shortcut3Icon ImageName #icon3H#][!UpdateMeter Shortcut3Icon][!Redraw][!SetOption Shortcut3 FontColor #colorSecondary#][!UpdateMeter Shortcut3][!Redraw]
MouseLeaveAction=[!SetOption Shortcut3Icon ImageName #icon3#][!UpdateMeter Shortcut3Icon][!Redraw][!SetOption Shortcut3 FontColor #colorMain#][!UpdateMeter Shortcut3][!Redraw]
X=30
Y=-1r

[Shortcut4Icon]
Meter=Image
ImageName=#icon4#
X=10
Y=12R
H=15
W=15
LeftMouseUpAction=["#path4#"]
MouseOverAction=[Play #soundsPath#\hover.wav][!SetOption Shortcut4Icon ImageName #icon4H#][!UpdateMeter Shortcut4Icon][!Redraw][!SetOption Shortcut4 FontColor #colorSecondary#][!UpdateMeter Shortcut4][!Redraw]
MouseLeaveAction=[!SetOption Shortcut4Icon ImageName #icon4#][!UpdateMeter Shortcut4Icon][!Redraw][!SetOption Shortcut4 FontColor #colorMain#][!UpdateMeter Shortcut4][!Redraw]

[Shortcut4]
Meter=String
MeterStyle=styleShortcut
Text=#text4#
LeftMouseUpAction=["#path4#"]
MouseOverAction=[Play #soundsPath#\hover.wav][!SetOption Shortcut4Icon ImageName #icon4H#][!UpdateMeter Shortcut4Icon][!Redraw][!SetOption Shortcut4 FontColor #colorSecondary#][!UpdateMeter Shortcut4][!Redraw]
MouseLeaveAction=[!SetOption Shortcut4Icon ImageName #icon4#][!UpdateMeter Shortcut4Icon][!Redraw][!SetOption Shortcut4 FontColor #colorMain#][!UpdateMeter Shortcut4][!Redraw]
X=30
Y=-1r

[Shortcut5Icon]
Meter=Image
ImageName=#icon5#
X=10
Y=12R
H=15
W=15
LeftMouseUpAction=["#path5#"]
MouseOverAction=[Play #soundsPath#\hover.wav][!SetOption Shortcut5Icon ImageName #icon5H#][!UpdateMeter Shortcut5Icon][!Redraw][!SetOption Shortcut5 FontColor #colorSecondary#][!UpdateMeter Shortcut5][!Redraw]
MouseLeaveAction=[!SetOption Shortcut5Icon ImageName #icon5#][!UpdateMeter Shortcut5Icon][!Redraw][!SetOption Shortcut5 FontColor #colorMain#][!UpdateMeter Shortcut5][!Redraw]

[Shortcut5]
Meter=String
MeterStyle=styleShortcut
Text=#text5#
LeftMouseUpAction=["#path5#"]
MouseOverAction=[Play #soundsPath#\hover.wav][!SetOption Shortcut5Icon ImageName #icon5H#][!UpdateMeter Shortcut5Icon][!Redraw][!SetOption Shortcut5 FontColor #colorSecondary#][!UpdateMeter Shortcut5][!Redraw]
MouseLeaveAction=[!SetOption Shortcut5Icon ImageName #icon5#][!UpdateMeter Shortcut5Icon][!Redraw][!SetOption Shortcut5 FontColor #colorMain#][!UpdateMeter Shortcut5][!Redraw]
X=30
Y=-1r

[Shortcut6Icon]
Meter=Image
ImageName=#icon6#
X=358
Y=-110r
H=15
W=15
LeftMouseUpAction=["#path6#"]
MouseOverAction=[Play #soundsPath#\hover.wav][!SetOption Shortcut6Icon ImageName #icon6H#][!UpdateMeter Shortcut6Icon][!Redraw][!SetOption Shortcut6 FontColor #colorSecondary#][!UpdateMeter Shortcut6][!Redraw]
MouseLeaveAction=[!SetOption Shortcut6Icon ImageName #icon6#][!UpdateMeter Shortcut6Icon][!Redraw][!SetOption Shortcut6 FontColor #colorMain#][!UpdateMeter Shortcut6][!Redraw]

[Shortcut6]
Meter=String
MeterStyle=styleShortcutRight
Text=#Text6#
LeftMouseUpAction=["#Path6#"]
MouseOverAction=[Play #soundsPath#\hover.wav][!SetOption Shortcut6Icon ImageName #icon6H#][!UpdateMeter Shortcut6Icon][!Redraw][!SetOption Shortcut6 FontColor #colorSecondary#][!UpdateMeter Shortcut6][!Redraw]
MouseLeaveAction=[!SetOption Shortcut6Icon ImageName #icon6#][!UpdateMeter Shortcut6Icon][!Redraw][!SetOption Shortcut6 FontColor #colorMain#][!UpdateMeter Shortcut6][!Redraw]
X=-5r
Y=-1r


[Shortcut7Icon]
Meter=Image
ImageName=#icon7#
X=358
Y=12R
H=15
W=15
LeftMouseUpAction=["#path7#"]
MouseOverAction=[Play #soundsPath#\hover.wav][!SetOption Shortcut7Icon ImageName #icon7H#][!UpdateMeter Shortcut7Icon][!Redraw][!SetOption Shortcut7 FontColor #colorSecondary#][!UpdateMeter Shortcut7][!Redraw]
MouseLeaveAction=[!SetOption Shortcut7Icon ImageName #icon7#][!UpdateMeter Shortcut7Icon][!Redraw][!SetOption Shortcut7 FontColor #colorMain#][!UpdateMeter Shortcut7][!Redraw]

[Shortcut7]
Meter=String
MeterStyle=styleShortcutRight
Text=#text7#
LeftMouseUpAction=["#path7#"]
MouseOverAction=[Play #soundsPath#\hover.wav][!SetOption Shortcut7Icon ImageName #icon7H#][!UpdateMeter Shortcut7Icon][!Redraw][!SetOption Shortcut7 FontColor #colorSecondary#][!UpdateMeter Shortcut7][!Redraw]
MouseLeaveAction=[!SetOption Shortcut7Icon ImageName #icon7#][!UpdateMeter Shortcut7Icon][!Redraw][!SetOption Shortcut7 FontColor #colorMain#][!UpdateMeter Shortcut7][!Redraw]
X=-5r
Y=-1r

[Shortcut8Icon]
Meter=Image
ImageName=#icon8#
X=358
Y=12R
H=15
W=15
LeftMouseUpAction=["#path8#"]
MouseOverAction=[Play #soundsPath#\hover.wav][!SetOption Shortcut8Icon ImageName #icon8H#][!UpdateMeter Shortcut8Icon][!Redraw][!SetOption Shortcut8 FontColor #colorSecondary#][!UpdateMeter Shortcut8][!Redraw]
MouseLeaveAction=[!SetOption Shortcut8Icon ImageName #icon8#][!UpdateMeter Shortcut8Icon][!Redraw][!SetOption Shortcut8 FontColor #colorMain#][!UpdateMeter Shortcut8][!Redraw]

[Shortcut8]
Meter=String
MeterStyle=styleShortcutRight
Text=#text8#
LeftMouseUpAction=["#path8#"]
MouseOverAction=[Play #soundsPath#\hover.wav][!SetOption Shortcut8Icon ImageName #icon8H#][!UpdateMeter Shortcut8Icon][!Redraw][!SetOption Shortcut8 FontColor #colorSecondary#][!UpdateMeter Shortcut8][!Redraw]
MouseLeaveAction=[!SetOption Shortcut8Icon ImageName #icon8#][!UpdateMeter Shortcut8Icon][!Redraw][!SetOption Shortcut8 FontColor #colorMain#][!UpdateMeter Shortcut8][!Redraw]
X=-5r
Y=-1r

[Shortcut9Icon]
Meter=Image
ImageName=#icon9#
X=358
Y=12R
H=15
W=15
LeftMouseUpAction=["#path9#"]
MouseOverAction=[Play #soundsPath#\hover.wav][!SetOption Shortcut9Icon ImageName #icon9H#][!UpdateMeter Shortcut9Icon][!Redraw][!SetOption Shortcut9 FontColor #colorSecondary#][!UpdateMeter Shortcut9][!Redraw]
MouseLeaveAction=[!SetOption Shortcut9Icon ImageName #icon9#][!UpdateMeter Shortcut9Icon][!Redraw][!SetOption Shortcut9 FontColor #colorMain#][!UpdateMeter Shortcut9][!Redraw]

[Shortcut9]
Meter=String
MeterStyle=styleShortcutRight
Text=#text9#
LeftMouseUpAction=["#path9#"]
MouseOverAction=[Play #soundsPath#\hover.wav][!SetOption Shortcut9Icon ImageName #icon9H#][!UpdateMeter Shortcut9Icon][!Redraw][!SetOption Shortcut9 FontColor #colorSecondary#][!UpdateMeter Shortcut9][!Redraw]
MouseLeaveAction=[!SetOption Shortcut9Icon ImageName #icon9#][!UpdateMeter Shortcut9Icon][!Redraw][!SetOption Shortcut9 FontColor #colorMain#][!UpdateMeter Shortcut9][!Redraw]
X=-5r
Y=-1r

[Shortcut10Icon]
Meter=Image
ImageName=#icon10#
X=358
Y=12R
H=15
W=15
LeftMouseUpAction=["#path10#"]
MouseOverAction=[Play #soundsPath#\hover.wav][!SetOption Shortcut10Icon ImageName #icon10H#][!UpdateMeter Shortcut10Icon][!Redraw][!SetOption Shortcut10 FontColor #colorSecondary#][!UpdateMeter Shortcut10][!Redraw]
MouseLeaveAction=[!SetOption Shortcut10Icon ImageName #icon10#][!UpdateMeter Shortcut10Icon][!Redraw][!SetOption Shortcut10 FontColor #colorMain#][!UpdateMeter Shortcut10][!Redraw]

[Shortcut10]
Meter=String
MeterStyle=styleShortcutRight
Text=#text10#
LeftMouseUpAction=["#path10#"]
MouseOverAction=[Play #soundsPath#\hover.wav][!SetOption Shortcut10Icon ImageName #icon10H#][!UpdateMeter Shortcut10Icon][!Redraw][!SetOption Shortcut10 FontColor #colorSecondary#][!UpdateMeter Shortcut10][!Redraw]
MouseLeaveAction=[!SetOption Shortcut10Icon ImageName #icon10#][!UpdateMeter Shortcut10Icon][!Redraw][!SetOption Shortcut10 FontColor #colorMain#][!UpdateMeter Shortcut10][!Redraw]
X=-5r
Y=-1r